# Generated by Django 4.1 on 2022-08-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(blank=True, help_text='URL of the Image', max_length=255, null=True, verbose_name='URL')),
                ('media', models.FileField(help_text='Image File', upload_to='images/', verbose_name='File')),
                ('width', models.PositiveIntegerField(blank=True, help_text='Width of the image', null=True, verbose_name='Width')),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height of the image', null=True, verbose_name='Height')),
                ('size', models.PositiveIntegerField(blank=True, help_text='Size of the document in KB', null=True, verbose_name='Size')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
